<div>
  <?php if (count($flash) > 0) : ?>
    <?php foreach ($flash as $messages) : ?>
      <?php foreach ($messages as $message) :?>
        <li><?= $message ?></li>
      <?php endforeach ?>
    <?php endforeach ?>
  <?php endif ?>
</div>

<a href='/posts?page=<?= $page - 1 ?>'>Previous</a>
<a href='/posts?page=<?= $page + 1 ?>'>Next</a>
</Br>
<a href='/posts/new'>New post</a>

<table>
  <?php foreach ($posts as $post) : ?>
    <tr>
      <td>
        <a href='/posts/<?= htmlspecialchars($post['id']) ?>'>
          <?= htmlspecialchars($post['name']) ?>
        </a>
        <form action="/posts/<?= htmlspecialchars($post['id'])?>" method='post'>
          <input type="hidden" name="_METHOD" value="DELETE">
          <input type='submit' value='Delete'>
        </form>
      </td>
    </tr>
  <?php endforeach ?>
</table>

<td>Page:<?= $page ?></td>


<?php foreach ($posts as $post): ?>
  <div>
    <?= htmlspecialchars($post['name']) ?>
    <form action="/posts/<?= $post['id'] ?>" method="post">
      <input type="hidden" name="_METHOD" value="DELETE">
      <input type="submit" value="Delete">
    </form>
  </div>
<?php endforeach ?>
